version: "3.3"

services:
#  current versions
  process:
    image: pirs/process:0.2.1
    build:
      context: ./pkg
      dockerfile: process/Dockerfile
  process-storage:
    image: pirs/process-storage:0.2.1
    build:
      context: ./pkg
      dockerfile: process-storage/Dockerfile

# tagging as latest
  process-storage_latest:
    depends_on:
      - process-storage
    image: pirs/process-storage:latest
    build:
      context: ./pkg
      dockerfile: process-storage/Dockerfile
  process_latest:
    depends_on:
      - process
    image: pirs/process:latest
    build:
      context: ./pkg
      dockerfile: process/Dockerfile
