// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: process-storage.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoding int32

const (
	Encoding_UTF8 Encoding = 0
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "UTF8",
	}
	Encoding_value = map[string]int32{
		"UTF8": 0,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_process_storage_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_process_storage_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{0}
}

type ProcessType int32

const (
	ProcessType_PETRIFLOW ProcessType = 0
	ProcessType_BPMN      ProcessType = 1
)

// Enum value maps for ProcessType.
var (
	ProcessType_name = map[int32]string{
		0: "PETRIFLOW",
		1: "BPMN",
	}
	ProcessType_value = map[string]int32{
		"PETRIFLOW": 0,
		"BPMN":      1,
	}
)

func (x ProcessType) Enum() *ProcessType {
	p := new(ProcessType)
	*p = x
	return p
}

func (x ProcessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessType) Descriptor() protoreflect.EnumDescriptor {
	return file_process_storage_proto_enumTypes[1].Descriptor()
}

func (ProcessType) Type() protoreflect.EnumType {
	return &file_process_storage_proto_enumTypes[1]
}

func (x ProcessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessType.Descriptor instead.
func (ProcessType) EnumDescriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{1}
}

type UploadStatus int32

const (
	UploadStatus_PENDING     UploadStatus = 0
	UploadStatus_IN_PROGRESS UploadStatus = 1
	UploadStatus_SUCCESS     UploadStatus = 2
	UploadStatus_FAILED      UploadStatus = 3
)

// Enum value maps for UploadStatus.
var (
	UploadStatus_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "SUCCESS",
		3: "FAILED",
	}
	UploadStatus_value = map[string]int32{
		"PENDING":     0,
		"IN_PROGRESS": 1,
		"SUCCESS":     2,
		"FAILED":      3,
	}
)

func (x UploadStatus) Enum() *UploadStatus {
	p := new(UploadStatus)
	*p = x
	return p
}

func (x UploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_process_storage_proto_enumTypes[2].Descriptor()
}

func (UploadStatus) Type() protoreflect.EnumType {
	return &file_process_storage_proto_enumTypes[2]
}

func (x UploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatus.Descriptor instead.
func (UploadStatus) EnumDescriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{2}
}

type ProcessUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ProcessFileData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ProcessUploadRequest) Reset() {
	*x = ProcessUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUploadRequest) ProtoMessage() {}

func (x *ProcessUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUploadRequest.ProtoReflect.Descriptor instead.
func (*ProcessUploadRequest) Descriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessUploadRequest) GetData() *ProcessFileData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProcessUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UploadStatus `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.UploadStatus" json:"status,omitempty"`
}

func (x *ProcessUploadResponse) Reset() {
	*x = ProcessUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUploadResponse) ProtoMessage() {}

func (x *ProcessUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUploadResponse.ProtoReflect.Descriptor instead.
func (*ProcessUploadResponse) Descriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessUploadResponse) GetStatus() UploadStatus {
	if x != nil {
		return x.Status
	}
	return UploadStatus_PENDING
}

type ProcessMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId string      `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Filename  string      `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Encoding  Encoding    `protobuf:"varint,3,opt,name=encoding,proto3,enum=grpc.Encoding" json:"encoding,omitempty"`
	Type      ProcessType `protobuf:"varint,4,opt,name=type,proto3,enum=grpc.ProcessType" json:"type,omitempty"`
}

func (x *ProcessMetadata) Reset() {
	*x = ProcessMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetadata) ProtoMessage() {}

func (x *ProcessMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_process_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetadata.ProtoReflect.Descriptor instead.
func (*ProcessMetadata) Descriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessMetadata) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ProcessMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ProcessMetadata) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_UTF8
}

func (x *ProcessMetadata) GetType() ProcessType {
	if x != nil {
		return x.Type
	}
	return ProcessType_PETRIFLOW
}

type ProcessFileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*ProcessFileData_Metadata
	//	*ProcessFileData_Chunk
	Data isProcessFileData_Data `protobuf_oneof:"data"`
}

func (x *ProcessFileData) Reset() {
	*x = ProcessFileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFileData) ProtoMessage() {}

func (x *ProcessFileData) ProtoReflect() protoreflect.Message {
	mi := &file_process_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFileData.ProtoReflect.Descriptor instead.
func (*ProcessFileData) Descriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{3}
}

func (m *ProcessFileData) GetData() isProcessFileData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ProcessFileData) GetMetadata() *ProcessMetadata {
	if x, ok := x.GetData().(*ProcessFileData_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *ProcessFileData) GetChunk() []byte {
	if x, ok := x.GetData().(*ProcessFileData_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isProcessFileData_Data interface {
	isProcessFileData_Data()
}

type ProcessFileData_Metadata struct {
	Metadata *ProcessMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ProcessFileData_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ProcessFileData_Metadata) isProcessFileData_Data() {}

func (*ProcessFileData_Chunk) isProcessFileData_Data() {}

type ProcessDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
}

func (x *ProcessDownloadRequest) Reset() {
	*x = ProcessDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDownloadRequest) ProtoMessage() {}

func (x *ProcessDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDownloadRequest.ProtoReflect.Descriptor instead.
func (*ProcessDownloadRequest) Descriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessDownloadRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type ProcessDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ProcessFileData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ProcessDownloadResponse) Reset() {
	*x = ProcessDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDownloadResponse) ProtoMessage() {}

func (x *ProcessDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDownloadResponse.ProtoReflect.Descriptor instead.
func (*ProcessDownloadResponse) Descriptor() ([]byte, []int) {
	return file_process_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessDownloadResponse) GetData() *ProcessFileData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_process_storage_proto protoreflect.FileDescriptor

var file_process_storage_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x41, 0x0a,
	0x14, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x43, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x66, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x33, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x37, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x14,
	0x0a, 0x08, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x54,
	0x46, 0x38, 0x10, 0x00, 0x2a, 0x26, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x54, 0x52, 0x49, 0x46, 0x4c, 0x4f, 0x57,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x50, 0x4d, 0x4e, 0x10, 0x01, 0x2a, 0x45, 0x0a, 0x0c,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f,
	0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x03, 0x32, 0xad, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12,
	0x4e, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x52, 0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_process_storage_proto_rawDescOnce sync.Once
	file_process_storage_proto_rawDescData = file_process_storage_proto_rawDesc
)

func file_process_storage_proto_rawDescGZIP() []byte {
	file_process_storage_proto_rawDescOnce.Do(func() {
		file_process_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_process_storage_proto_rawDescData)
	})
	return file_process_storage_proto_rawDescData
}

var file_process_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_process_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_process_storage_proto_goTypes = []interface{}{
	(Encoding)(0),                   // 0: grpc.Encoding
	(ProcessType)(0),                // 1: grpc.ProcessType
	(UploadStatus)(0),               // 2: grpc.UploadStatus
	(*ProcessUploadRequest)(nil),    // 3: grpc.ProcessUploadRequest
	(*ProcessUploadResponse)(nil),   // 4: grpc.ProcessUploadResponse
	(*ProcessMetadata)(nil),         // 5: grpc.ProcessMetadata
	(*ProcessFileData)(nil),         // 6: grpc.ProcessFileData
	(*ProcessDownloadRequest)(nil),  // 7: grpc.ProcessDownloadRequest
	(*ProcessDownloadResponse)(nil), // 8: grpc.ProcessDownloadResponse
}
var file_process_storage_proto_depIdxs = []int32{
	6, // 0: grpc.ProcessUploadRequest.data:type_name -> grpc.ProcessFileData
	2, // 1: grpc.ProcessUploadResponse.status:type_name -> grpc.UploadStatus
	0, // 2: grpc.ProcessMetadata.encoding:type_name -> grpc.Encoding
	1, // 3: grpc.ProcessMetadata.type:type_name -> grpc.ProcessType
	5, // 4: grpc.ProcessFileData.metadata:type_name -> grpc.ProcessMetadata
	6, // 5: grpc.ProcessDownloadResponse.data:type_name -> grpc.ProcessFileData
	3, // 6: grpc.Storage.UploadProcess:input_type -> grpc.ProcessUploadRequest
	7, // 7: grpc.Storage.DownloadProcess:input_type -> grpc.ProcessDownloadRequest
	4, // 8: grpc.Storage.UploadProcess:output_type -> grpc.ProcessUploadResponse
	8, // 9: grpc.Storage.DownloadProcess:output_type -> grpc.ProcessDownloadResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_process_storage_proto_init() }
func file_process_storage_proto_init() {
	if File_process_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_process_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessFileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_process_storage_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ProcessFileData_Metadata)(nil),
		(*ProcessFileData_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_process_storage_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_storage_proto_goTypes,
		DependencyIndexes: file_process_storage_proto_depIdxs,
		EnumInfos:         file_process_storage_proto_enumTypes,
		MessageInfos:      file_process_storage_proto_msgTypes,
	}.Build()
	File_process_storage_proto = out.File
	file_process_storage_proto_rawDesc = nil
	file_process_storage_proto_goTypes = nil
	file_process_storage_proto_depIdxs = nil
}
