apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: pirs
spec:
  serviceName: mongo-db
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:4.4
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: pr_mongoName
                  name: pirs-cfg
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: pr_mongoPass
                  name: pirs-cfg
          ports:
            - containerPort: 27017
              protocol: TCP
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: pirs
  labels:
    app: mongo-db
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-db
