// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: process.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProcessClient is the client API for Process service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessClient interface {
	ImportProcess(ctx context.Context, in *ImportProcessRequest, opts ...grpc.CallOption) (*ImportProcessResponse, error)
	ImportPackage(ctx context.Context, in *ImportPackageRequest, opts ...grpc.CallOption) (*ImportPackageResponse, error)
	RemoveProcess(ctx context.Context, in *RemoveProcessRequest, opts ...grpc.CallOption) (*RemoveProcessResponse, error)
	DownloadProcess(ctx context.Context, in *DownloadProcessRequest, opts ...grpc.CallOption) (*DownloadProcessResponse, error)
}

type processClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessClient(cc grpc.ClientConnInterface) ProcessClient {
	return &processClient{cc}
}

func (c *processClient) ImportProcess(ctx context.Context, in *ImportProcessRequest, opts ...grpc.CallOption) (*ImportProcessResponse, error) {
	out := new(ImportProcessResponse)
	err := c.cc.Invoke(ctx, "/grpc.Process/ImportProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processClient) ImportPackage(ctx context.Context, in *ImportPackageRequest, opts ...grpc.CallOption) (*ImportPackageResponse, error) {
	out := new(ImportPackageResponse)
	err := c.cc.Invoke(ctx, "/grpc.Process/ImportPackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processClient) RemoveProcess(ctx context.Context, in *RemoveProcessRequest, opts ...grpc.CallOption) (*RemoveProcessResponse, error) {
	out := new(RemoveProcessResponse)
	err := c.cc.Invoke(ctx, "/grpc.Process/RemoveProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processClient) DownloadProcess(ctx context.Context, in *DownloadProcessRequest, opts ...grpc.CallOption) (*DownloadProcessResponse, error) {
	out := new(DownloadProcessResponse)
	err := c.cc.Invoke(ctx, "/grpc.Process/DownloadProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessServer is the server API for Process service.
// All implementations must embed UnimplementedProcessServer
// for forward compatibility
type ProcessServer interface {
	ImportProcess(context.Context, *ImportProcessRequest) (*ImportProcessResponse, error)
	ImportPackage(context.Context, *ImportPackageRequest) (*ImportPackageResponse, error)
	RemoveProcess(context.Context, *RemoveProcessRequest) (*RemoveProcessResponse, error)
	DownloadProcess(context.Context, *DownloadProcessRequest) (*DownloadProcessResponse, error)
	mustEmbedUnimplementedProcessServer()
}

// UnimplementedProcessServer must be embedded to have forward compatible implementations.
type UnimplementedProcessServer struct {
}

func (UnimplementedProcessServer) ImportProcess(context.Context, *ImportProcessRequest) (*ImportProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportProcess not implemented")
}
func (UnimplementedProcessServer) ImportPackage(context.Context, *ImportPackageRequest) (*ImportPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportPackage not implemented")
}
func (UnimplementedProcessServer) RemoveProcess(context.Context, *RemoveProcessRequest) (*RemoveProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProcess not implemented")
}
func (UnimplementedProcessServer) DownloadProcess(context.Context, *DownloadProcessRequest) (*DownloadProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadProcess not implemented")
}
func (UnimplementedProcessServer) mustEmbedUnimplementedProcessServer() {}

// UnsafeProcessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessServer will
// result in compilation errors.
type UnsafeProcessServer interface {
	mustEmbedUnimplementedProcessServer()
}

func RegisterProcessServer(s grpc.ServiceRegistrar, srv ProcessServer) {
	s.RegisterService(&Process_ServiceDesc, srv)
}

func _Process_ImportProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServer).ImportProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Process/ImportProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServer).ImportProcess(ctx, req.(*ImportProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Process_ImportPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServer).ImportPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Process/ImportPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServer).ImportPackage(ctx, req.(*ImportPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Process_RemoveProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServer).RemoveProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Process/RemoveProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServer).RemoveProcess(ctx, req.(*RemoveProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Process_DownloadProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServer).DownloadProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Process/DownloadProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServer).DownloadProcess(ctx, req.(*DownloadProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Process_ServiceDesc is the grpc.ServiceDesc for Process service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Process_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Process",
	HandlerType: (*ProcessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportProcess",
			Handler:    _Process_ImportProcess_Handler,
		},
		{
			MethodName: "ImportPackage",
			Handler:    _Process_ImportPackage_Handler,
		},
		{
			MethodName: "RemoveProcess",
			Handler:    _Process_RemoveProcess_Handler,
		},
		{
			MethodName: "DownloadProcess",
			Handler:    _Process_DownloadProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "process.proto",
}
