FROM golang:1.19-bullseye

## install protoc
RUN apt-get update
RUN apt-get install -y protobuf-compiler

# install go protoc deps
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install github.com/envoyproxy/protoc-gen-validate@latest

# copy all application files
WORKDIR /app
