FROM golang:1.19-bullseye

ARG APP_NAME=process-storage
ARG APP_DIR=/process-storage

## install protoc
RUN apt-get update
RUN apt-get install -y protobuf-compiler

# install go protoc deps
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install github.com/envoyproxy/protoc-gen-validate@latest

# copy all application files
WORKDIR /$APP_DIR

COPY . ./

# generate go files from proto
RUN cd ./grpc && ./generate.sh
# install deps && build app
RUN go install
RUN go build -o bin/$APP_NAME

EXPOSE 40005
ENTRYPOINT ["bin/${APP_NAME}"]
